version: "2.3"

services:
  proxy-can-lynx:
    image: registry.git.chalmers.se/cfs/driverless20/cfsd-proxy-can-lynx:v0.0.1
    restart: on-failure
    network_mode: host
    command: "--cid=111 --freq=0.5 --can=vcan0 --verbose" 
