version: "2.3"
services:
    proxy-safetylayer-lynx:
        container_name: proxy-safetylayer-lynx
        build:
            context: ./cfsd-proxy-safetylayer
            dockerfile: Dockerfile
        image: cfsd-proxy-safetylayer:latest       
        #image: registry.git.chalmers.se/cfs/driverless20/cfsd-proxy-safetylayer:v0.0.2
        restart: on-failure
        network_mode: "host"
        command: "cfsd-proxy-safetylayer --verbosedata --verbose --freq=30 --cid=111"
        # sender stamps 5000

    proxy-can-lynx:
        container_name: proxy-can-lynx
        build:
           context: ./cfsd-proxy-can-lynx
           dockerfile: Dockerfile
        image: cfsd-proxy-can-lynx:latest       
        #image: registry.git.chalmers.se/cfs/driverless20/cfsd-proxy-can-lynx:v0.0.2
        restart: on-failure
        network_mode: host
        depends_on:
        - "proxy-safetylayer-lynx"
        command: "--cid=111 --freq=30 --can=vcan0 --verbose" 
