/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 32.6.3 Thu Jul 16 13:28:08 2020.
 */

#ifndef LYNX19GW_H
#define LYNX19GW_H

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

#define LYNX19GW_TEST_FRAME_ID (0xc8u)
#define LYNX19GW_MOTOR_CONTROL_MESSAGE_FRAME_ID (0x10u)
#define LYNX19GW_FRONT_NODE_FRAME_ID (0x11u)

/**
 * Signals in message Test.
 *
 * All signal values are as on the CAN bus.
 */
struct lynx19gw_test_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t test_message;
};

/**
 * Signals in message MOTOR_CONTROL_MESSAGE.
 *
 * All signal values are as on the CAN bus.
 */
struct lynx19gw_motor_control_message_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint8_t pwm_enabled;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint16_t torque_setpoint;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint16_t speed_setpoint;

    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    uint16_t max_power_setpoint;
};

/**
 * Signals in message Front_Node.
 *
 * All signal values are as on the CAN bus.
 */
struct lynx19gw_front_node_t {
    /**
     * Range: -
     * Scale: 1
     * Offset: 0
     */
    double apps_value;
};

/**
 * Pack message Test.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
inline int lynx19gw_test_pack(
    uint8_t *dst_p,
    const struct lynx19gw_test_t *src_p,
    size_t size);

/**
 * Unpack message Test.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
inline int lynx19gw_test_unpack(
    struct lynx19gw_test_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
inline uint8_t lynx19gw_test_test_message_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
inline double lynx19gw_test_test_message_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
inline bool lynx19gw_test_test_message_is_in_range(uint8_t value);

/**
 * Pack message MOTOR_CONTROL_MESSAGE.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
inline int lynx19gw_motor_control_message_pack(
    uint8_t *dst_p,
    const struct lynx19gw_motor_control_message_t *src_p,
    size_t size);

/**
 * Unpack message MOTOR_CONTROL_MESSAGE.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
inline int lynx19gw_motor_control_message_unpack(
    struct lynx19gw_motor_control_message_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
inline uint8_t lynx19gw_motor_control_message_pwm_enabled_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
inline double lynx19gw_motor_control_message_pwm_enabled_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
inline bool lynx19gw_motor_control_message_pwm_enabled_is_in_range(uint8_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
inline uint16_t lynx19gw_motor_control_message_torque_setpoint_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
inline double lynx19gw_motor_control_message_torque_setpoint_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
inline bool lynx19gw_motor_control_message_torque_setpoint_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
inline uint16_t lynx19gw_motor_control_message_speed_setpoint_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
inline double lynx19gw_motor_control_message_speed_setpoint_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
inline bool lynx19gw_motor_control_message_speed_setpoint_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
inline uint16_t lynx19gw_motor_control_message_max_power_setpoint_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
inline double lynx19gw_motor_control_message_max_power_setpoint_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
inline bool lynx19gw_motor_control_message_max_power_setpoint_is_in_range(uint16_t value);

/**
 * Pack message Front_Node.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
inline int lynx19gw_front_node_pack(
    uint8_t *dst_p,
    const struct lynx19gw_front_node_t *src_p,
    size_t size);

/**
 * Unpack message Front_Node.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
inline int lynx19gw_front_node_unpack(
    struct lynx19gw_front_node_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
inline double lynx19gw_front_node_apps_value_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
inline double lynx19gw_front_node_apps_value_decode(double value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
inline bool lynx19gw_front_node_apps_value_is_in_range(double value);

#endif
/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 32.6.3 Thu Jul 16 13:28:08 2020.
 */

#include <string.h>

//#include "lynx19gw.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int lynx19gw_test_pack(
    uint8_t *dst_p,
    const struct lynx19gw_test_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->test_message, 0u, 0xffu);

    return (1);
}

int lynx19gw_test_unpack(
    struct lynx19gw_test_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->test_message |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

uint8_t lynx19gw_test_test_message_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_test_test_message_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_test_test_message_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int lynx19gw_motor_control_message_pack(
    uint8_t *dst_p,
    const struct lynx19gw_motor_control_message_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 7);

    dst_p[0] |= pack_left_shift_u8(src_p->pwm_enabled, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->torque_setpoint, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->torque_setpoint, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u16(src_p->speed_setpoint, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u16(src_p->speed_setpoint, 8u, 0xffu);
    dst_p[5] |= pack_left_shift_u16(src_p->max_power_setpoint, 0u, 0xffu);
    dst_p[6] |= pack_right_shift_u16(src_p->max_power_setpoint, 8u, 0xffu);

    return (7);
}

int lynx19gw_motor_control_message_unpack(
    struct lynx19gw_motor_control_message_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 7u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    dst_p->pwm_enabled |= unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->torque_setpoint |= unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->torque_setpoint |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->speed_setpoint |= unpack_right_shift_u16(src_p[3], 0u, 0xffu);
    dst_p->speed_setpoint |= unpack_left_shift_u16(src_p[4], 8u, 0xffu);
    dst_p->max_power_setpoint |= unpack_right_shift_u16(src_p[5], 0u, 0xffu);
    dst_p->max_power_setpoint |= unpack_left_shift_u16(src_p[6], 8u, 0xffu);

    return (0);
}

uint8_t lynx19gw_motor_control_message_pwm_enabled_encode(double value)
{
    return (uint8_t)(value);
}

double lynx19gw_motor_control_message_pwm_enabled_decode(uint8_t value)
{
    return ((double)value);
}

bool lynx19gw_motor_control_message_pwm_enabled_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_motor_control_message_torque_setpoint_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_motor_control_message_torque_setpoint_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_motor_control_message_torque_setpoint_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_motor_control_message_speed_setpoint_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_motor_control_message_speed_setpoint_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_motor_control_message_speed_setpoint_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t lynx19gw_motor_control_message_max_power_setpoint_encode(double value)
{
    return (uint16_t)(value);
}

double lynx19gw_motor_control_message_max_power_setpoint_decode(uint16_t value)
{
    return ((double)value);
}

bool lynx19gw_motor_control_message_max_power_setpoint_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int lynx19gw_front_node_pack(
    uint8_t *dst_p,
    const struct lynx19gw_front_node_t *src_p,
    size_t size)
{
    uint16_t apps_value;

    if (size < 2u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 2);

    memcpy(&apps_value, &src_p->apps_value, sizeof(apps_value));
    dst_p[0] |= pack_left_shift_u16(apps_value, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(apps_value, 8u, 0xffu);

    return (2);
}

int lynx19gw_front_node_unpack(
    struct lynx19gw_front_node_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t apps_value;

    if (size < 2u) {
        return (-EINVAL);
    }

    memset(dst_p, 0, sizeof(*dst_p));

    apps_value = 0u;
    apps_value |= unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    apps_value |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    memcpy(&dst_p->apps_value, &apps_value, sizeof(dst_p->apps_value));

    return (0);
}

double lynx19gw_front_node_apps_value_encode(double value)
{
    return (double)(value);
}

double lynx19gw_front_node_apps_value_decode(double value)
{
    return ((double)value);
}

bool lynx19gw_front_node_apps_value_is_in_range(double value)
{
    (void)value;

    return (true);
}

/*
 * THIS IS AN AUTO-GENERATED FILE. DO NOT MODIFY AS CHANGES MIGHT BE OVERWRITTEN!
 */

#ifndef VISITABLE_TYPE_TRAIT
#define VISITABLE_TYPE_TRAIT
#include <cstdint>
#include <string>
#include <utility>

template<bool b>
struct visitorSelector {
    template<typename T, class Visitor>
    static void impl(uint32_t fieldIdentifier, std::string &&typeName, std::string &&name, T &value, Visitor &visitor) {
        visitor.visit(fieldIdentifier, std::move(typeName), std::move(name), value);
    }
};

template<>
struct visitorSelector<true> {
    template<typename T, class Visitor>
    static void impl(uint32_t fieldIdentifier, std::string &&typeName, std::string &&name, T &value, Visitor &visitor) {
        visitor.visit(fieldIdentifier, std::move(typeName), std::move(name), value);
    }
};

template<typename T>
struct isVisitable {
    static const bool value = false;
};

template<typename T, class Visitor>
void doVisit(uint32_t fieldIdentifier, std::string &&typeName, std::string &&name, T &value, Visitor &visitor) {
    visitorSelector<isVisitable<T>::value >::impl(fieldIdentifier, std::move(typeName), std::move(name), value, visitor);
}
#endif

#ifndef TRIPLET_FORWARD_VISITABLE_TYPE_TRAIT
#define TRIPLET_FORWARD_VISITABLE_TYPE_TRAIT
#include <cstdint>
#include <string>
#include <utility>

template<bool b>
struct tripletForwardVisitorSelector {
    template<typename T, class PreVisitor, class Visitor, class PostVisitor>
    static void impl(uint32_t fieldIdentifier, std::string &&typeName, std::string &&name, T &value, PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit) {
        (void)preVisit;
        (void)postVisit;
        std::forward<Visitor>(visit)(fieldIdentifier, std::move(typeName), std::move(name), value);
    }
};

template<>
struct tripletForwardVisitorSelector<true> {
    template<typename T, class PreVisitor, class Visitor, class PostVisitor>
    static void impl(uint32_t fieldIdentifier, std::string &&typeName, std::string &&name, T &value, PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit) {
        (void)fieldIdentifier;
        (void)typeName;
        (void)name;
        // Apply preVisit, visit, and postVisit on value.
        value.accept(preVisit, visit, postVisit);
    }
};

template<typename T>
struct isTripletForwardVisitable {
    static const bool value = false;
};

template< typename T, class PreVisitor, class Visitor, class PostVisitor>
void doTripletForwardVisit(uint32_t fieldIdentifier, std::string &&typeName, std::string &&name, T &value, PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit) {
    tripletForwardVisitorSelector<isTripletForwardVisitable<T>::value >::impl(fieldIdentifier, std::move(typeName), std::move(name), value, std::move(preVisit), std::move(visit), std::move(postVisit)); // NOLINT
}
#endif


#ifndef OPENDLV_PROXY_TEST_HPP
#define OPENDLV_PROXY_TEST_HPP

#ifdef WIN32
    // Export symbols if compile flags "LIB_SHARED" and "LIB_EXPORTS" are set on Windows.
    #ifdef LIB_SHARED
        #ifdef LIB_EXPORTS
            #define LIB_API __declspec(dllexport)
        #else
            #define LIB_API __declspec(dllimport)
        #endif
    #else
        // Disable definition if linking statically.
        #define LIB_API
    #endif
#else
    // Disable definition for non-Win32 systems.
    #define LIB_API
#endif

#include <string>
#include <utility>
namespace opendlv { namespace proxy {
using namespace std::string_literals; // NOLINT
class LIB_API Test {
    private:
        static constexpr const char* TheShortName = "Test";
        static constexpr const char* TheLongName = "opendlv.proxy.Test";

    public:
        inline static int32_t ID() {
            return 1001;
        }
        inline static const std::string ShortName() {
            return TheShortName;
        }
        inline static const std::string LongName() {
            return TheLongName;
        }

    public:
        Test() = default;
        Test(const Test&) = default;
        Test& operator=(const Test&) = default;
        Test(Test&&) = default;
        Test& operator=(Test&&) = default;
        ~Test() = default;

    public:
        
        inline Test& testMessage(const int &v) noexcept {
            m_testMessage = v;
            return *this;
        }
        inline int testMessage() const noexcept {
            return m_testMessage;
        }
        

    public:
        template<class Visitor>
        inline void accept(uint32_t fieldId, Visitor &visitor) {
            (void)fieldId;
            (void)visitor;
//            visitor.preVisit(ID(), ShortName(), LongName());
            
            if (1 == fieldId) {
                doVisit(1, std::move("int"s), std::move("testMessage"s), m_testMessage, visitor);
                return;
            }
            
//            visitor.postVisit();
        }

        template<class Visitor>
        inline void accept(Visitor &visitor) {
            visitor.preVisit(ID(), ShortName(), LongName());
            
            doVisit(1, std::move("int"s), std::move("testMessage"s), m_testMessage, visitor);
            
            visitor.postVisit();
        }

        template<class PreVisitor, class Visitor, class PostVisitor>
        inline void accept(PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit) {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            
            doTripletForwardVisit(1, std::move("int"s), std::move("testMessage"s), m_testMessage, preVisit, visit, postVisit);
            
            std::forward<PostVisitor>(postVisit)();
        }

    private:
        
        int m_testMessage{  }; // field identifier = 1.
        
};
}}

template<>
struct isVisitable<opendlv::proxy::Test> {
    static const bool value = true;
};
template<>
struct isTripletForwardVisitable<opendlv::proxy::Test> {
    static const bool value = true;
};
#endif


/*
 * THIS IS AN AUTO-GENERATED FILE. DO NOT MODIFY AS CHANGES MIGHT BE OVERWRITTEN!
 */

#ifndef VISITABLE_TYPE_TRAIT
#define VISITABLE_TYPE_TRAIT
#include <cstdint>
#include <string>
#include <utility>

template<bool b>
struct visitorSelector {
    template<typename T, class Visitor>
    static void impl(uint32_t fieldIdentifier, std::string &&typeName, std::string &&name, T &value, Visitor &visitor) {
        visitor.visit(fieldIdentifier, std::move(typeName), std::move(name), value);
    }
};

template<>
struct visitorSelector<true> {
    template<typename T, class Visitor>
    static void impl(uint32_t fieldIdentifier, std::string &&typeName, std::string &&name, T &value, Visitor &visitor) {
        visitor.visit(fieldIdentifier, std::move(typeName), std::move(name), value);
    }
};

template<typename T>
struct isVisitable {
    static const bool value = false;
};

template<typename T, class Visitor>
void doVisit(uint32_t fieldIdentifier, std::string &&typeName, std::string &&name, T &value, Visitor &visitor) {
    visitorSelector<isVisitable<T>::value >::impl(fieldIdentifier, std::move(typeName), std::move(name), value, visitor);
}
#endif

#ifndef TRIPLET_FORWARD_VISITABLE_TYPE_TRAIT
#define TRIPLET_FORWARD_VISITABLE_TYPE_TRAIT
#include <cstdint>
#include <string>
#include <utility>

template<bool b>
struct tripletForwardVisitorSelector {
    template<typename T, class PreVisitor, class Visitor, class PostVisitor>
    static void impl(uint32_t fieldIdentifier, std::string &&typeName, std::string &&name, T &value, PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit) {
        (void)preVisit;
        (void)postVisit;
        std::forward<Visitor>(visit)(fieldIdentifier, std::move(typeName), std::move(name), value);
    }
};

template<>
struct tripletForwardVisitorSelector<true> {
    template<typename T, class PreVisitor, class Visitor, class PostVisitor>
    static void impl(uint32_t fieldIdentifier, std::string &&typeName, std::string &&name, T &value, PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit) {
        (void)fieldIdentifier;
        (void)typeName;
        (void)name;
        // Apply preVisit, visit, and postVisit on value.
        value.accept(preVisit, visit, postVisit);
    }
};

template<typename T>
struct isTripletForwardVisitable {
    static const bool value = false;
};

template< typename T, class PreVisitor, class Visitor, class PostVisitor>
void doTripletForwardVisit(uint32_t fieldIdentifier, std::string &&typeName, std::string &&name, T &value, PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit) {
    tripletForwardVisitorSelector<isTripletForwardVisitable<T>::value >::impl(fieldIdentifier, std::move(typeName), std::move(name), value, std::move(preVisit), std::move(visit), std::move(postVisit)); // NOLINT
}
#endif


#ifndef OPENDLV_PROXY_SENSORS_HPP
#define OPENDLV_PROXY_SENSORS_HPP

#ifdef WIN32
    // Export symbols if compile flags "LIB_SHARED" and "LIB_EXPORTS" are set on Windows.
    #ifdef LIB_SHARED
        #ifdef LIB_EXPORTS
            #define LIB_API __declspec(dllexport)
        #else
            #define LIB_API __declspec(dllimport)
        #endif
    #else
        // Disable definition if linking statically.
        #define LIB_API
    #endif
#else
    // Disable definition for non-Win32 systems.
    #define LIB_API
#endif

#include <string>
#include <utility>
namespace opendlv { namespace proxy {
using namespace std::string_literals; // NOLINT
class LIB_API Sensors {
    private:
        static constexpr const char* TheShortName = "Sensors";
        static constexpr const char* TheLongName = "opendlv.proxy.Sensors";

    public:
        inline static int32_t ID() {
            return 1002;
        }
        inline static const std::string ShortName() {
            return TheShortName;
        }
        inline static const std::string LongName() {
            return TheLongName;
        }

    public:
        Sensors() = default;
        Sensors(const Sensors&) = default;
        Sensors& operator=(const Sensors&) = default;
        Sensors(Sensors&&) = default;
        Sensors& operator=(Sensors&&) = default;
        ~Sensors() = default;

    public:
        
        inline Sensors& appsValue(const float &v) noexcept {
            m_appsValue = v;
            return *this;
        }
        inline float appsValue() const noexcept {
            return m_appsValue;
        }
        

    public:
        template<class Visitor>
        inline void accept(uint32_t fieldId, Visitor &visitor) {
            (void)fieldId;
            (void)visitor;
//            visitor.preVisit(ID(), ShortName(), LongName());
            
            if (1 == fieldId) {
                doVisit(1, std::move("float"s), std::move("appsValue"s), m_appsValue, visitor);
                return;
            }
            
//            visitor.postVisit();
        }

        template<class Visitor>
        inline void accept(Visitor &visitor) {
            visitor.preVisit(ID(), ShortName(), LongName());
            
            doVisit(1, std::move("float"s), std::move("appsValue"s), m_appsValue, visitor);
            
            visitor.postVisit();
        }

        template<class PreVisitor, class Visitor, class PostVisitor>
        inline void accept(PreVisitor &&preVisit, Visitor &&visit, PostVisitor &&postVisit) {
            (void)visit; // Prevent warnings from empty messages.
            std::forward<PreVisitor>(preVisit)(ID(), ShortName(), LongName());
            
            doTripletForwardVisit(1, std::move("float"s), std::move("appsValue"s), m_appsValue, preVisit, visit, postVisit);
            
            std::forward<PostVisitor>(postVisit)();
        }

    private:
        
        float m_appsValue{ 0.0f }; // field identifier = 1.
        
};
}}

template<>
struct isVisitable<opendlv::proxy::Sensors> {
    static const bool value = true;
};
template<>
struct isTripletForwardVisitable<opendlv::proxy::Sensors> {
    static const bool value = true;
};
#endif

